package testkit

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// FakeOutcome is what the fake runner reports for one case in one run.
type FakeOutcome string

const (
	FakePass FakeOutcome = "pass"
	FakeFail FakeOutcome = "fail"
)

// FakeCase is one test case the fake runner reports. Runs holds the outcome
// per invocation and its last entry repeats, so a stable case needs one entry
// and a flaky one needs as many as the probe count.
type FakeCase struct {
	File string
	Name string
	Runs []FakeOutcome
}

// FakeRunner stands in for a project's .redfirst/test.sh. It counts its own
// invocations in a file, honours $REDFIRST_FILTER and writes JUnit XML to
// $REDFIRST_RESULTS. The counter is how a flake gets simulated without a real
// test framework.
type FakeRunner struct {
	t *testing.T
	// Script is the executable path handed to the harness.
	Script  string
	counter string
}

// NewFakeRunner writes the runner to script, creating parent directories.
func NewFakeRunner(t *testing.T, script string, cases []FakeCase) *FakeRunner {
	t.Helper()

	counter := script + ".runs"
	if err := os.MkdirAll(filepath.Dir(script), 0o755); err != nil {
		t.Fatalf("mkdir for %s: %v", script, err)
	}
	if err := os.WriteFile(script, []byte(fakeRunnerScript(counter, cases)), 0o755); err != nil {
		t.Fatalf("write %s: %v", script, err)
	}
	return &FakeRunner{t: t, Script: script, counter: counter}
}

// Runs is how many times the script has executed.
func (f *FakeRunner) Runs() int {
	f.t.Helper()

	data, err := os.ReadFile(f.counter)
	if errors.Is(err, fs.ErrNotExist) {
		return 0
	}
	if err != nil {
		f.t.Fatalf("read run counter: %v", err)
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		f.t.Fatalf("run counter holds %q: %v", data, err)
	}
	return n
}

func fakeRunnerScript(counter string, cases []FakeCase) string {
	var b strings.Builder
	b.WriteString(fakeRunnerPrelude)
	fmt.Fprintf(&b, "counter=%s\n", shellQuote(counter))
	b.WriteString(fakeRunnerBody)
	for _, c := range cases {
		outcomes := make([]string, 0, len(c.Runs))
		for _, o := range c.Runs {
			outcomes = append(outcomes, string(o))
		}
		if len(outcomes) == 0 {
			outcomes = append(outcomes, string(FakePass))
		}
		fmt.Fprintf(&b, "emit %s %s %s\n",
			shellQuote(c.File), shellQuote(xmlEscape(c.Name)), shellQuote(strings.Join(outcomes, " ")))
	}
	b.WriteString(fakeRunnerEpilogue)
	return b.String()
}

const fakeRunnerPrelude = `#!/bin/sh
# Generated by internal/testkit. Do not edit.
set -u
`

// The braces around the emit calls group their output without forking, so
// failed survives the redirection.
const fakeRunnerBody = `n=$(cat "$counter" 2>/dev/null || echo 0)
n=$((n + 1))
printf '%s' "$n" > "$counter"

filter="${REDFIRST_FILTER:-}"
results="${REDFIRST_RESULTS:-/dev/null}"
failed=0

matches() {
	if [ -z "$filter" ]; then return 0; fi
	for f in $filter; do
		if [ "$f" = "$1" ]; then return 0; fi
	done
	return 1
}

# emit <file> <case name> <outcome per run>
emit() {
	if ! matches "$1"; then return 0; fi
	outcome=pass
	idx=0
	for o in $3; do
		idx=$((idx + 1))
		outcome="$o"
		if [ "$idx" -ge "$n" ]; then break; fi
	done
	if [ "$outcome" = fail ]; then
		failed=1
		printf '    <testcase classname="%s" name="%s"><failure message="fake failure"/></testcase>\n' "$1" "$2"
	else
		printf '    <testcase classname="%s" name="%s"/>\n' "$1" "$2"
	fi
}

{
	printf '<?xml version="1.0" encoding="UTF-8"?>\n'
	printf '<testsuites>\n  <testsuite name="fake">\n'
`

const fakeRunnerEpilogue = `	printf '  </testsuite>\n</testsuites>\n'
} > "$results"

exit "$failed"
`

func xmlEscape(s string) string {
	return strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&apos;",
	).Replace(s)
}
