package testkit

import (
	"strconv"
	"strings"
	"time"
)

// The hooks below stand in for a project's .redfirst/ directory. They bring no
// services up: what a fixture needs is a test runner whose answer depends on
// the tree it runs in, because that is the whole of red-green.
//
// The runner reads the test files themselves. A line
//
//	// case: applies a discount | needs: discount
//
// names a case and the marker the sources have to carry for it to pass;
// `flaky` makes the outcome follow $REDFIRST_PROBE_INDEX, `broken` fails
// always, `flaky-with: X` fails until the marker arrives and turns flaky once
// it has, and a bare name passes always. A file-level line
//
//	// requires: discount
//
// kills the run before a single case is reported, the way a compile error does.
//
// A marker is looked for outside the test files, so a case naming its own
// marker cannot satisfy itself: the overlay puts the head test file on the base
// sources, and a grep that read the test file would find every marker there.

// Hooks are the choices a fixture makes about its harness.
type Hooks struct {
	// Reset adds env-reset.sh, which is what picks the reused mode.
	Reset bool
	// Nameless makes the runner report results without per-case names, the way
	// a runner that only reports files does.
	Nameless bool
	// Log is a file every hook appends a line to, outside the run directory so
	// that teardown does not take it. It is how a test sees the order of the
	// phases and the number of runs inside one.
	Log string
	// Cost is what one run of test.sh is made to take. A real project spends
	// that time installing dependencies, building and running its suite, and
	// the benchmark that measures the core's share of a tier 2 run needs
	// something to measure the share against.
	Cost time.Duration
}

// WriteHooks puts the hook set into .redfirst/ of the current branch. The
// caller commits.
func WriteHooks(r *Repo, h Hooks) {
	r.t.Helper()

	prelude := strings.Replace(hookPrelude, "@LOG@", shellQuote(h.Log), 1)
	r.WriteScript(".redfirst/env-up.sh", prelude+"note env-up\n")
	r.WriteScript(".redfirst/env-down.sh", prelude+"note env-down\n")
	if h.Reset {
		r.WriteScript(".redfirst/env-reset.sh", prelude+"note env-reset\n")
	}
	nameless := "0"
	if h.Nameless {
		nameless = "1"
	}
	runner := strings.Replace(fixtureRunner, "@NAMELESS@", nameless, 1)
	runner = strings.Replace(runner, "@COST@", strconv.FormatFloat(h.Cost.Seconds(), 'f', -1, 64), 1)
	r.WriteScript(".redfirst/test.sh", prelude+runner)
}

const hookPrelude = `#!/bin/sh
# Generated by internal/testkit. Do not edit.
set -u

log=@LOG@
note() {
	if [ -n "$log" ]; then printf '%s\n' "$*" >> "$log"; fi
}
`

const fixtureRunner = `note "test ${REDFIRST_PHASE:-?} ${REDFIRST_PROBE_INDEX:-?}"

cost=@COST@
if [ "$cost" != 0 ]; then sleep "$cost"; fi

results="${REDFIRST_RESULTS:-/dev/null}"
index="${REDFIRST_PROBE_INDEX:-1}"
nameless=@NAMELESS@

files="${REDFIRST_FILTER:-}"
if [ -z "$files" ]; then
	files=$(find . -type f -name '*.test.*' | sed 's|^\./||' | sort)
fi

present=""
for f in $files; do
	if [ -f "$f" ]; then present="$present $f"; fi
done

# The marker of a case is looked for outside the test files: the overlay puts
# the head test file onto the base sources, and a case naming its own marker
# would otherwise pass on base and prove nothing.
sources=$(find . -type f ! -name '*.test.*' ! -path './.redfirst/*' | sort)

has() {
	if [ -z "$sources" ]; then return 1; fi
	grep -q -- "$1" $sources 2>/dev/null
}

# A file-level requirement the sources do not meet kills the run before a
# single case is reported, the way a compile error does.
for f in $present; do
	need=$(sed -n 's|^// requires: ||p' "$f")
	if [ -n "$need" ] && ! has "$need"; then
		echo "cannot build $f: $need is undefined" >&2
		exit 1
	fi
done

failed=0
{
	printf '<?xml version="1.0" encoding="UTF-8"?>\n<testsuites>\n  <testsuite name="fixture">\n'
	for f in $present; do
		while IFS= read -r line; do
			case "$line" in
			'// case: '*) ;;
			*) continue ;;
			esac

			body=${line#// case: }
			name=$(printf '%s' "${body%%|*}" | sed 's| *$||')
			rule=""
			case "$body" in
			*'|'*) rule=$(printf '%s' "${body#*|}" | sed 's|^ *||; s| *$||') ;;
			esac

			ok=1
			case "$rule" in
			'') ;;
			flaky) if [ $((index % 2)) -eq 1 ]; then ok=0; fi ;;
			broken) ok=0 ;;
			needs:*) if ! has "$(printf '%s' "${rule#needs:}" | sed 's|^ *||')"; then ok=0; fi ;;
			flaky-with:*)
				if ! has "$(printf '%s' "${rule#flaky-with:}" | sed 's|^ *||')"; then
					ok=0
				elif [ $((index % 2)) -eq 1 ]; then
					ok=0
				fi
				;;
			*)
				echo "unknown rule \"$rule\" in $f" >&2
				exit 1
				;;
			esac

			if [ "$nameless" = 1 ]; then name=""; fi
			if [ "$ok" = 1 ]; then
				printf '    <testcase classname="%s" name="%s"/>\n' "$f" "$name"
			else
				failed=1
				printf '    <testcase classname="%s" name="%s"><failure message="fixture"/></testcase>\n' "$f" "$name"
			fi
		done < "$f"
	done
	printf '  </testsuite>\n</testsuites>\n'
} > "$results"

exit "$failed"
`

// shellQuote wraps a path for a hook that interpolates it. An empty path stays
// an empty string, which is what switches the logging off.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
