package cliux

import (
	"strconv"
	"strings"

	"github.com/timhartmann7/redfirst/internal/config"
)

// The strict set for agent branches. Everything else in the generated file
// comes from the built-in defaults, so the two never drift apart.
//
// The split follows the one new-test-present already makes: the defaults judge
// human pull requests and stay out of the way, and the template judges an agent.
// A snapshot rewritten to match wrong output, a test file hollowed out, a
// twenty-file diff for a one-line fix: all three are ordinary on a human branch
// and almost always mean bending the result on an agent one.
const (
	strictMaxFiles        = 8
	strictMaxAddedLines   = 300
	strictMaxDeletedLines = 120
)

// configTOML renders the file `redfirst init --config` writes.
func configTOML() string {
	cfg := config.Defaults()
	return strings.NewReplacer(
		"__MAX_FILES__", strconv.Itoa(strictMaxFiles),
		"__MAX_ADDED__", strconv.Itoa(strictMaxAddedLines),
		"__MAX_DELETED__", strconv.Itoa(strictMaxDeletedLines),
		"__PROTECTED__", tomlList(cfg.Paths.Protected.Raw()),
		"__GUARDED__", tomlList(cfg.Paths.Guarded.Raw()),
		"__PATTERNS__", tomlList(cfg.Tests.Patterns.Raw()),
		"__FIXTURES__", tomlList(cfg.Tests.Fixtures.Raw()),
		"__FORBID_DISABLED__", tomlList(cfg.Tests.ForbidDisabled.Raw()),
		"__SUPPRESSION__", tomlList(cfg.Suppression.Patterns.Raw()),
		"__PROBE_RUNS__", strconv.Itoa(cfg.RedGreen.ProbeRuns),
		"__COMPILE_FAILURE__", tomlString(string(cfg.RedGreen.CompileFailureOnBase)),
		"__RETRY_FAILED__", strconv.Itoa(cfg.Suite.RetryFailed),
		"__CROSS_SCOPE__", strconv.FormatBool(cfg.Scopes.AllowCrossScope),
	).Replace(configTemplate)
}

const configTemplate = `# Generated by ` + "`redfirst init --config`" + `.
#
# redfirst reads this file from the base branch, so an edit on a branch under
# judgement changes nothing about how that branch is judged. Keep the path in
# paths.protected below and let a human review every change to it.
#
# A key you set replaces its default whole; a key you leave out keeps the
# built-in one. Sections are not the unit of replacement, and lists never merge.
# ` + "`redfirst explain`" + ` prints the set that came out.
#
# The values here are stricter than the built-in defaults, which judge human
# pull requests: budget 20 / 800 / 400, immutability "append-only",
# fixtures_immutability "warn", require_new false, diff-budget a warning.
version = 1

[budget]
# Numbers for agent branches. Yours are in your own history:
# ` + "`redfirst audit --last 50 --per-pr --report csv`" + ` prints the distribution,
# and the upper quartile of it makes a limit nobody argues with.
max_files = __MAX_FILES__
max_added_lines = __MAX_ADDED__
max_deleted_lines = __MAX_DELETED__

[paths]
# Blocking. An edit to any of these changes the rules the agent is judged by.
protected = [
__PROTECTED__
]
# Under observation: these reach the report and leave the verdict alone.
guarded = [
__GUARDED__
]
# When non-empty, the diff may touch ONLY these paths.
allowed = []

[tests]
patterns = [
__PATTERNS__
]
# The test surface: files that decide test outcomes without holding test cases.
fixtures = [
__FIXTURES__
]
# strict      - an existing test file is neither modified nor deleted
# append-only - modifications allowed while no line is deleted
# cases       - edits allowed while no existing case disappeared or went red on
#               head. Needs hooks; without them it downgrades to append-only.
immutability = "cases"
# The same values plus warn, which only flags an edit in the report.
fixtures_immutability = "strict"
require_new = true
forbid_disabled = [
__FORBID_DISABLED__
]
# Known unstable tests, fully exempt from suite-green.
known_flaky = []

[red_green]
enabled = true
# How many times a probe runs. Every run has to return the same result: a red
# that comes and goes would acquit a test that never caught anything.
probe_runs = __PROBE_RUNS__
# How to count a new test that fails to build on base.
# red | weak-red (red, and said so in the report) | fail
compile_failure_on_base = __COMPILE_FAILURE__

[suite]
# How many times to rerun a failed test before classifying it.
retry_failed = __RETRY_FAILED__

[suppression]
# Warnings in the report, no effect on the verdict.
enabled = true
patterns = [
__SUPPRESSION__
]

[severity]
# fail - a violation blocks, warn - a report line.
# Lowering red-green or suite-green to warn is refused: exit code 3.
diff-budget = "fail"

[gates]
# Selective disabling by id. An empty list runs every gate.
disabled = []

[scopes]
# Whether a diff may cross scope boundaries. For an autonomous agent, false is
# the recommendation. Scopes themselves are not implemented in v1: a [[scope]]
# section is exit code 3.
allow_cross_scope = __CROSS_SCOPE__
`
