package cliux

import (
	"fmt"
	"os"
	"strings"

	"github.com/timhartmann7/redfirst/internal/harness"
)

// The hook names of the contract in section 7 of the spec. Three are required
// for tier 2; env-reset.sh is what picks the reused environment mode, and
// env.sh is sourced ahead of the rest rather than executed.
const (
	hookCompose = "compose.yaml"
	hookEnv     = "env.sh"
	hookUp      = "env-up.sh"
	hookReset   = "env-reset.sh"
	hookTest    = "test.sh"
	hookDown    = "env-down.sh"
)

// script is the mode a hook needs. redfirst executes a hook directly and
// honours its shebang, so a file without the bit is a broken harness rather
// than a red test.
const (
	script os.FileMode = 0o755
	data   os.FileMode = 0o644
)

// hookFile is one generated file. Most are scripts; the compose file of the
// docker preset is data the scripts read, so the mode travels with the file.
type hookFile struct {
	name string
	body string
	mode os.FileMode
}

// PresetNames lists what --hooks accepts, for the flag help and for a refusal.
func PresetNames() string {
	names := make([]string, 0, len(Presets()))
	for _, p := range Presets() {
		names = append(names, string(p))
	}
	return strings.Join(names, ", ")
}

// InitHooks writes the hook set of a preset into .redfirst/.
//
// PresetAuto asks the repository's own markers which set to write and returns
// the answer, because somebody who named no preset has to see the one they got.
func InitHooks(root string, p Preset) (Preset, []string, error) {
	if p == PresetAuto {
		picked, err := Detect(root).Preset()
		if err != nil {
			return "", nil, err
		}
		p = picked
	}
	files, known := hookSets()[p]
	if !known {
		return "", nil, fmt.Errorf("unknown hook preset %q, want one of %s", p, PresetNames())
	}

	// The whole set is checked before any of it lands. Half a hook set is the
	// one state the contract has no name for, and a refusal on the third file
	// would leave it behind.
	for _, f := range files {
		if err := free(root, hookPath(f.name)); err != nil {
			return "", nil, err
		}
	}
	written := make([]string, 0, len(files))
	for _, f := range files {
		at, err := write(root, hookPath(f.name), header(p, f.name)+f.body, f.mode)
		if err != nil {
			return "", nil, err
		}
		written = append(written, at)
	}
	return p, written, nil
}

func hookPath(name string) string { return harness.HooksDir + "/" + name }

// header opens every generated hook. The file says where its own rules live
// before it says what it runs: redfirst reads this directory from the base
// branch, so an edit on a branch under judgement changes nothing.
//
// env.sh gets no `set -eu`. It is sourced rather than executed, and a `set -e`
// that outlives the sourcing would let one failed command end the shell that
// was about to run the hook.
func header(p Preset, name string) string {
	if name == hookCompose {
		// Not a script, so no shebang and no shell flags. The note it carries
		// is the same one, in the comment syntax of the file it opens.
		return fmt.Sprintf(`# Generated by `+"`redfirst init --hooks %s`"+`.
#
# redfirst copies %s/ out of the base branch and runs the hooks
# there, so this file decides what the services are, and an edit on a branch
# under judgement does not reach it.
`, p, harness.HooksDir)
	}
	head := fmt.Sprintf(`#!/bin/sh
# Generated by `+"`redfirst init --hooks %s`"+`.
#
# redfirst copies %s/ out of the base branch and runs it there, so an
# edit on a branch under judgement changes nothing about how that branch is
# judged. Keep %s/** in paths.protected and let a human review every
# change to it.
`, p, harness.HooksDir, harness.HooksDir)

	switch name {
	case hookEnv:
		// Sourced rather than executed. A `set -e` that outlives the sourcing
		// would let one failed command end the shell that was about to run the
		// hook, and the run would take that for a hook that passed.
		return head
	case hookDown:
		// No set -e either, and for the opposite reason. The generated file
		// carries the why: a reader who does not find it there restores the
		// flag, and the teardown starts leaking services again.
		return head + `set -u
# No set -e: this hook runs on the panic path and on the deadline, when half
# the environment was never built, and stopping at the first command that finds
# nothing to stop would leak the rest. A non-zero exit here is exit code 2.
`
	}
	return head + "set -eu\n"
}

// hookSets is what each preset writes. Every test.sh here obeys the same four
// rules, and each of them is one silent way to make red-green worthless:
// restrict the run to $REDFIRST_FILTER, write per-case names to
// $REDFIRST_RESULTS, install and build only on the first run of a phase, and
// never hand back the result of the run before.
func hookSets() map[Preset][]hookFile {
	return map[Preset][]hookFile{
		PresetNodeUnit: {
			{hookUp, nodeUnitUp, script},
			{hookTest, nodeUnitTest, script},
			{hookDown, noServicesDown, script},
		},
		PresetNodePostgres: {
			{hookCompose, postgresCompose, data},
			{hookEnv, postgresEnv, script},
			{hookUp, postgresUp, script},
			{hookReset, postgresReset, script},
			{hookTest, postgresTest, script},
			{hookDown, postgresDown, script},
		},
		PresetPythonPytest: {
			{hookUp, pytestUp, script},
			{hookTest, pytestTest, script},
			{hookDown, noServicesDown, script},
		},
		PresetGo: {
			{hookUp, goUp, script},
			{hookTest, goTest, script},
			{hookDown, noServicesDown, script},
		},
		PresetBlank: {
			{hookUp, blankUp, script},
			{hookTest, blankTest, script},
			{hookDown, blankDown, script},
		},
	}
}

// noServicesDown is the teardown of a project with nothing to tear down. The
// file still has to exist and still has to exit 0.
const noServicesDown = `
# Nothing was brought up here, so there is nothing to stop.
exit 0
`

// toolCheck says why every preset spends its env-up.sh on one command. The
// distinction it draws is the one the exit code contract rests on.
const toolCheck = `
# A missing toolchain is a broken repository, not a failing test, and this hook
# is where the difference can still be told: a non-zero exit here is exit code
# 2, while a non-zero exit from test.sh means the suite went red.
`

const nodeUnitUp = toolCheck + `command -v pnpm >/dev/null 2>&1 || {
	echo "pnpm is not on PATH" >&2
	exit 1
}
`

const nodeUnitTest = `
# Every run of a phase shares one working copy, so the install happens once.
# Repeating it per run would cost probe_runs installs for a single pull request.
if [ "$REDFIRST_PROBE_INDEX" = 1 ]; then
	pnpm install --frozen-lockfile
fi

# The collection gets a step of its own, and that is the opposite of tidiness.
# A test file that does not resolve its imports is reported by vitest run as a
# case named after the file, and red-green reads a name it did not see on base
# as a case the diff added: red on base, gone from head once the fix is there,
# which refuses the honest fix that adds a module together with the test for it.
# A tree that does not collect has no case to report, so this step leaves
# $REDFIRST_RESULTS empty instead, which is what
# red_green.compile_failure_on_base is there to rule on.
#
# vitest list collects without running, so nothing executes twice here.
if ! pnpm exec vitest list $REDFIRST_FILTER >/dev/null; then
	echo "the test files under $REDFIRST_FILTER do not collect" >&2
	exit 1
fi

# $REDFIRST_FILTER is left unquoted on purpose: it carries a list of files, and
# an empty one has to run the whole suite.
#
# vitest run executes the tests on every invocation, which is what makes the
# probe_runs runs of red-green three answers rather than one. --no-cache keeps
# the transform cache in the shared working copy from being what differs
# between the first probe and the third.
#
# Never add --passWithNoTests. It turns a filter that matched nothing into a
# green run, which is the one silent pass red-green exists to catch.
#
# jest instead of vitest: pnpm exec jest --ci --reporters=jest-junit, with
# JEST_JUNIT_OUTPUT_FILE="$REDFIRST_RESULTS" exported above.
pnpm exec vitest run --no-cache \
	--reporter=junit --outputFile="$REDFIRST_RESULTS" $REDFIRST_FILTER
`

const pytestUp = toolCheck + `command -v python3 >/dev/null 2>&1 || {
	echo "python3 is not on PATH" >&2
	exit 1
}
`

const pytestTest = `
# Dot prefixed and inside the working copy: pytest skips it while collecting,
# and the copy is rebuilt for every phase, so the base tree and the head tree
# never share an installed package.
venv=.redfirst-venv

# A requirements.txt project writes: "$venv/bin/pip" install -r requirements.txt
if [ "$REDFIRST_PROBE_INDEX" = 1 ]; then
	python3 -m venv "$venv"
	"$venv/bin/pip" install --quiet --no-cache-dir --editable ".[dev]"
fi

# Not a tidiness flag. red-green overlays the head test files onto the base
# working copy, and cached bytecode is keyed on a file's size and its mtime in
# whole seconds: two versions of one test file can collide on both, and the
# probe would then execute the code of the run before it. A base probe that
# comes back green for that reason reads as "the test is green on base".
export PYTHONDONTWRITEBYTECODE=1

# The collection gets a step of its own, for the same reason the build does in
# a compiled language. A test module that cannot be imported is reported by
# pytest as a case named after the file, and red-green reads a name it did not
# see on base as a case the diff added: red on base, gone from head once the fix
# is there, which refuses the honest fix that adds a module together with the
# test for it. A tree that does not collect has no case to report, so this step
# leaves $REDFIRST_RESULTS empty instead, which is what
# red_green.compile_failure_on_base is there to rule on.
if ! "$venv/bin/pytest" --collect-only -q -p no:cacheprovider $REDFIRST_FILTER >/dev/null; then
	echo "the test modules under $REDFIRST_FILTER do not import" >&2
	exit 1
fi

# $REDFIRST_FILTER is left unquoted on purpose: it carries a list of files, and
# an empty one has to run the whole suite.
#
# --maxfail=0 overrides an addopts of -x: a report truncated at the first
# failure leaves red-green unable to tell a case that never ran from one that
# disappeared. -p no:cacheprovider keeps .pytest_cache out of the working copy.
"$venv/bin/pytest" --maxfail=0 -p no:cacheprovider \
	--junitxml="$REDFIRST_RESULTS" $REDFIRST_FILTER
`

const goUp = toolCheck + `command -v gotestsum >/dev/null 2>&1 || {
	echo "gotestsum is not on PATH: go install gotest.tools/gotestsum@v1.13.0" >&2
	exit 1
}
`

const goTest = `
# go test takes packages and $REDFIRST_FILTER names files, so every path
# becomes the package that owns it. testdata and fixture directories are not
# packages, the go tool ignores those names everywhere else, and the package
# that owns them is the one above. A path that maps to no package at all sends
# the run at the whole tree: too wide costs time, too narrow loses the case the
# verdict turns on.
packages=./...
if [ -n "${REDFIRST_FILTER:-}" ]; then
	packages=""
	for f in $REDFIRST_FILTER; do
		case "$f" in
		*/testdata/*) dir=${f%%/testdata/*} ;;
		*/fixtures/*) dir=${f%%/fixtures/*} ;;
		*) dir=$(dirname "$f") ;;
		esac
		if ! ls "$dir"/*.go >/dev/null 2>&1; then
			packages=./...
			break
		fi
		# Two changed test files in one package leave one entry.
		case " $packages " in
		*" ./$dir "*) continue ;;
		esac
		packages="$packages ./$dir"
	done
fi

# The build gets a step of its own, and that is the opposite of tidiness.
# gotestsum reports a package that fails to build as a case named TestMain, and
# red-green reads a name it did not see on base as a case the diff added: red on
# base, absent on head once the fix is there, which refuses the honest fix that
# adds an API together with the test for it. A tree that does not build has no
# case to report, so this step leaves $REDFIRST_RESULTS empty instead, which is
# what red_green.compile_failure_on_base is there to rule on.
#
# -run '^$' matches no test, so nothing executes here and the compile is warm
# for the run below.
if ! go test -run '^$' $packages >/dev/null; then
	echo "the packages under test do not build" >&2
	exit 1
fi

# -count=1 is not optional. Without it the Go test cache replays the verdict of
# the previous run, the probe_runs runs of red-green collapse into one, and a
# test that only sometimes fails passes for one that always does.
gotestsum --junitfile "$REDFIRST_RESULTS" --format testname -- -count=1 $packages
`

const blankUp = `
# Bring the services this project's tests need up, and exit 0 once they answer.
# $REDFIRST_RUN_ID is one value per redfirst run, shared by every phase and
# every probe inside it. Put it into every container, network, volume and port
# name, or two branches checked at once will fight over them.
#
# A non-zero exit here is exit code 2, a broken repository. That is the hook for
# a missing toolchain or a database that will not start.
#
# A project with no services leaves this file as it stands.
exit 0
`

const blankTest = `
# Run the tests of this project. This is the hook redfirst judges by, and five
# rules decide whether that judgement is worth anything.
#
# 1. $REDFIRST_FILTER carries a list of files. Run only those when it is
#    non-empty, and the whole suite when it is not. Leave it unquoted so an
#    empty value disappears. Without this the probes of red-green run the whole
#    suite probe_runs times over.
# 2. Write JUnit XML or TAP to $REDFIRST_RESULTS, with one entry per case and a
#    name on it. Without names red-green cannot tell a case the diff added from
#    one that was already there, and a diff touching an existing test file gets
#    exit code 5, which no diff the agent writes can answer.
# 3. Install dependencies and build only when $REDFIRST_PROBE_INDEX is 1. Every
#    run of a phase shares one working copy, so the rest is already built.
# 4. Decide the tree builds before reporting anything. A file that does not
#    build is reported by most runners as a case named after the file, and
#    red-green reads that as a case the diff added: red on base, gone from head
#    once the fix arrives. A tree that does not build has to leave
#    $REDFIRST_RESULTS empty instead.
# 5. Never hand back the result of the previous run. Runners that cache have a
#    flag for it: go test needs -count=1.
#
# $REDFIRST_WORKDIR is the working copy, and it is already the current
# directory. $REDFIRST_PHASE is base, head or suite.
#
# Exit 0 when the tests pass, non-zero when they do not.
#
# Committed as it stands, this refuses every diff: the suite comes back red and
# suite-green charges it to whoever opened the pull request. A repository not
# ready for tier 2 is better off with no ` + harness.HooksDir + `/ at all, which leaves
# red-green and suite-green unavailable and refuses nobody.
echo "` + hookTest + ` has not been filled in yet" >&2
exit 1
`

const blankDown = `
# Stop everything env-up.sh started.
exit 0
`
