package cliux

import "strings"

// PinnedRelease is the release a generated workflow installs.
//
// A binary cannot carry the checksum of an artifact that contains it, so what
// it pins is the newest release whose checksums were published before it was
// built. The release step fills the two constants below, which is what keeps
// `init` offline: the pin is compiled in rather than fetched, and the workflow
// it generates verifies a checksum anybody can recompute from the release.
func PinnedRelease() Release {
	return Release{Version: pinnedVersion, SHA256: pinnedSHA256}
}

// Filled by the release step. Empty here means this build predates the first
// release, and `init --ci` says so rather than generating an unpinned workflow.
const (
	pinnedVersion = ""
	pinnedSHA256  = ""
)

func workflowYAML(rel Release) string {
	return strings.NewReplacer(
		"__VERSION__", rel.Version,
		"__SHA256__", rel.SHA256,
	).Replace(workflowTemplate)
}

// workflowTemplate is the one file tier 1 adds to a repository.
//
// Two things in it are load-bearing rather than style. The version and the
// checksum are pinned together, so a moved tag stops the install instead of
// judging the diff with a binary nobody chose. And the base branch reaches the
// shell through the environment instead of an expression, because a branch name
// is somebody else's text and `run:` would execute it.
const workflowTemplate = `# Generated by ` + "`redfirst init --ci`" + `.
#
# This file decides what judges the repository, so treat it as a rule rather
# than a script: keep the path in paths.protected, protect the branch, and let a
# human review every change to it. redfirst reads its own config, hooks and
# rules from the base branch for the same reason.
name: redfirst

on:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      # Pinned together: a moved tag changes the checksum and the install stops.
      REDFIRST_VERSION: __VERSION__
      REDFIRST_SHA256: __SHA256__
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # The diff runs from the merge base, so the history both refs share
          # has to be in the clone.
          fetch-depth: 0

      - name: Install redfirst
        run: |
          set -eu
          asset="redfirst_${REDFIRST_VERSION#v}_linux_amd64.tar.gz"
          curl --fail --silent --show-error --location --output "$asset" \
            "https://github.com/timhartmann7/redfirst/releases/download/${REDFIRST_VERSION}/${asset}"
          printf '%s  %s\n' "$REDFIRST_SHA256" "$asset" | sha256sum --check --strict -
          tar --extract --gzip --file "$asset" redfirst

      - name: Verify the diff
        env:
          BASE_REF: ${{ github.base_ref }}
        run: ./redfirst verify --base "origin/$BASE_REF" --head HEAD
`
