#!/bin/sh
# Generated by `redfirst init --hooks go`.
#
# redfirst copies .redfirst/ out of the base branch and runs it there, so an
# edit on a branch under judgement changes nothing about how that branch is
# judged. Keep .redfirst/** in paths.protected and let a human review every
# change to it.
set -eu

# A missing toolchain is a broken repository, not a failing test, and this hook
# is where the difference can still be told: a non-zero exit here is exit code
# 2, while a non-zero exit from test.sh means the suite went red.
command -v gotestsum >/dev/null 2>&1 || {
	echo "gotestsum is not on PATH: go install gotest.tools/gotestsum@v1.13.0" >&2
	exit 1
}
