#!/bin/sh
# Generated by `redfirst init --hooks go`.
#
# redfirst copies .redfirst/ out of the base branch and runs it there, so an
# edit on a branch under judgement changes nothing about how that branch is
# judged. Keep .redfirst/** in paths.protected and let a human review every
# change to it.
set -eu

# go test takes packages and $REDFIRST_FILTER names files, so every path
# becomes the package that owns it. testdata and fixture directories are not
# packages, the go tool ignores those names everywhere else, and the package
# that owns them is the one above. A path that maps to no package at all sends
# the run at the whole tree: too wide costs time, too narrow loses the case the
# verdict turns on.
packages=./...
if [ -n "${REDFIRST_FILTER:-}" ]; then
	packages=""
	for f in $REDFIRST_FILTER; do
		case "$f" in
		*/testdata/*) dir=${f%%/testdata/*} ;;
		*/fixtures/*) dir=${f%%/fixtures/*} ;;
		*) dir=$(dirname "$f") ;;
		esac
		if ! ls "$dir"/*.go >/dev/null 2>&1; then
			packages=./...
			break
		fi
		# Two changed test files in one package leave one entry.
		case " $packages " in
		*" ./$dir "*) continue ;;
		esac
		packages="$packages ./$dir"
	done
fi

# -count=1 is not optional. Without it the Go test cache replays the verdict of
# the previous run, the probe_runs runs of red-green collapse into one, and a
# test that only sometimes fails passes for one that always does.
gotestsum --junitfile "$REDFIRST_RESULTS" --format testname -- -count=1 $packages
