#!/bin/sh
# Generated by `redfirst init --hooks go`.
#
# redfirst copies .redfirst/ out of the base branch and runs it there, so an
# edit on a branch under judgement changes nothing about how that branch is
# judged. Keep .redfirst/** in paths.protected and let a human review every
# change to it.
set -eu

# go test takes packages and $REDFIRST_FILTER names files, so every path
# becomes the package that owns it. testdata and fixture directories are not
# packages, the go tool ignores those names everywhere else, and the package
# that owns them is the one above. A path that maps to no package at all sends
# the run at the whole tree: too wide costs time, too narrow loses the case the
# verdict turns on.
packages=./...
if [ -n "${REDFIRST_FILTER:-}" ]; then
	packages=""
	for f in $REDFIRST_FILTER; do
		case "$f" in
		*/testdata/*) dir=${f%%/testdata/*} ;;
		*/fixtures/*) dir=${f%%/fixtures/*} ;;
		*) dir=$(dirname "$f") ;;
		esac
		if ! ls "$dir"/*.go >/dev/null 2>&1; then
			packages=./...
			break
		fi
		# Two changed test files in one package leave one entry.
		case " $packages " in
		*" ./$dir "*) continue ;;
		esac
		packages="$packages ./$dir"
	done
fi

# The build gets a step of its own, and that is the opposite of tidiness.
# gotestsum reports a package that fails to build as a case named TestMain, and
# red-green reads a name it did not see on base as a case the diff added: red on
# base, absent on head once the fix is there, which refuses the honest fix that
# adds an API together with the test for it. A tree that does not build has no
# case to report, so this step leaves $REDFIRST_RESULTS empty instead, which is
# what red_green.compile_failure_on_base is there to rule on.
#
# -run '^$' matches no test, so nothing executes here and the compile is warm
# for the run below.
if ! go test -run '^$' $packages >/dev/null; then
	echo "the packages under test do not build" >&2
	exit 1
fi

# -count=1 is not optional. Without it the Go test cache replays the verdict of
# the previous run, the probe_runs runs of red-green collapse into one, and a
# test that only sometimes fails passes for one that always does.
gotestsum --junitfile "$REDFIRST_RESULTS" --format testname -- -count=1 $packages
